# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "solarexplorer/sbfspot-sqlite:v3.8.3@sha256:9d8baccfcaff4e10dda077c510bc80071b579b70ff4657847e5ac1b4567e3f8f"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: SBFspot add-on"
  org.opencontainers.image.description: "Download data from an SMA® inverter over Bluetooth and publish them via MQTT."
  org.opencontainers.image.source: "https://github.com/swatchy2dot0/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT License"
