# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SBFspot add-on
version: "0.1.0"
slug: example
description: SBFspot add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armv7
  - amd64
init: false
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "swatchy2dot0/home-assistant-sbfspot"
