# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SBFspot add-on
version: "0.1.0"
slug: sbfspot
description: SBFspot add-on
url: "https://github.com/swatchy2dot0/home-assistant-addons/tree/main/sbfspot"
arch:
  - armv7
init: false
full_access: true
schema:
  message: "str?"
image: "swatchy2dot0/{arch}-home-assistant-sbfspot"
