# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
# docker run --rm --privileged -v ~/.docker:/root/.docker -v /<yourAddonsRootAbsolutePath>/home-assistant-addons/sbfspot:/data homeassistant/amd64-builder --armv7 -t /data
ARG BUILD_FROM
FROM $BUILD_FROM
